{
  "specName": "getapi.spec.js",
  "title": "get request",
  "suiteName": "sample test",
  "testName": "sample test get request",
  "testError": "cy.request() failed trying to load:\n\nhttp://fodqa11-iis3/api/v3/tenants\n\nWe attempted to make an http request to this URL but the request failed without a response.\n\nWe received this error at the network level:\n\n  > Error: connect ETIMEDOUT 16.103.234.239:80\n\n-----------------------------------------------------------\n\nThe request we sent was:\n\nMethod: GET\nURL: http://fodqa11-iis3/api/v3/tenants\n\n-----------------------------------------------------------\n\nCommon situations why this would fail:\n  - you don't have internet access\n  - you forgot to run / boot your web server\n  - your web server isn't accessible\n  - you have weird network configuration settings on your computer\n\nThe stack trace for this error is:\n\nRequestError: Error: connect ETIMEDOUT 16.103.234.239:80\n    at new RequestError (C:\\Users\\yliben\\AppData\\Local\\Cypress\\Cache\\3.4.1\\Cypress\\resources\\app\\packages\\server\\node_modules\\request-promise-core\\lib\\errors.js:14:15)\n    at Request.plumbing.callback (C:\\Users\\yliben\\AppData\\Local\\Cypress\\Cache\\3.4.1\\Cypress\\resources\\app\\packages\\server\\node_modules\\request-promise-core\\lib\\plumbing.js:87:29)\n    at Request.RP$callback [as _callback] (C:\\Users\\yliben\\AppData\\Local\\Cypress\\Cache\\3.4.1\\Cypress\\resources\\app\\packages\\server\\node_modules\\request-promise-core\\lib\\plumbing.js:46:31)\n    at self.callback (C:\\Users\\yliben\\AppData\\Local\\Cypress\\Cache\\3.4.1\\Cypress\\resources\\app\\packages\\server\\node_modules\\request\\request.js:185:22)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at Request.onRequestError (C:\\Users\\yliben\\AppData\\Local\\Cypress\\Cache\\3.4.1\\Cypress\\resources\\app\\packages\\server\\node_modules\\request\\request.js:881:8)\n    at emitOne (events.js:121:20)\n    at ClientRequest.emit (events.js:211:7)\n    at Socket.socketErrorListener (_http_client.js:387:9)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)\n",
  "testCommands": [
    "request "
  ],
  "screenshot": "get-request-failed.png"
}
